name: Build Xyaim dylib
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos & ldid
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "$HOME/theos/bin" >> $GITHUB_PATH
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          curl -Lo $HOME/theos/bin/ldid https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_arm64
          chmod +x $HOME/theos/bin/ldid
      - name: Build tweak
        run: |
          make package
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: Xyaim.deb
          path: packages/*.deb
